### ISSUE TITLE
Error: 'tag_name'

### ISSUE THREAD

**Issue by 0x00000a** [khast3x/h8mail#82]
* h8mail version: 2.5.2
* Python version: 3.6, 3.8
* Operating System:
- mac;
- win10;
- kali.

### Description
It works neither with python3.6 nor with python 3.8.
Docker also does not work and gives exactly the same error.
Commands used for pull and run in docker:
- docker pull kh4st3x00/h8mail
- docker run -ti kh4st3x00/h8mail -t olololo@alalal.com

### Output
root@kali://# h8mail -h
          Check out the new wiki!
          https://bit.ly/37xaQVh

          Version 2.5.2 - "ROCKSMASSON.2"

        ._____. ._____.     ;____________;
        | ._. | | ._. |     ;   h8mail   ;
        | !_| |_|_|_! |     ;------------;
        !___| |_______!  Heartfelt Email OSINT
        .___|_|_| |___.    Use responsibly
        | ._____| |_. | ;____________________;
        | !_! | | !_! | ; github.com/khast3x ;
        !_____! !_____! ;--------------------;

Traceback (most recent call last):
  File "/usr/local/bin/h8mail", line 11, in <module>
    load_entry_point('h8mail==2.5.2', 'console_scripts', 'h8mail')()
  File "/usr/local/lib/python3.8/dist-packages/h8mail/utils/run.py", line 354, in main
    check_latest_version()
  File "/usr/local/lib/python3.8/dist-packages/h8mail/utils/helpers.py", line 179, in check_latest_version
    latest = data["tag_name"]
KeyError: 'tag_name'

**Comment by 0x00000a** [comment]
FIxed if comment check_latest_version() function in main /usr/local/lib/python3.8/dist-packages/h8mail/utils/run.py

**Comment by khast3x** [comment]
Hello,

Re-ran tests to confirm that h8mail is functional. Your IP might be flagged by Github. Could you confirm it still does not work with another IP, using a VPN or running it on a remote VPS?

Cheers

**Comment by khast3x** [comment]
Fixed in v2.5.3
